import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-bg-secondary">
      <div className="max-w-[720px] mx-auto px-6 py-16">
        <Link
          href="/signup"
          className="inline-flex items-center gap-1.5 text-sm text-mono-light hover:text-mono-medium transition-colors mb-10"
        >
          <span className="material-symbols-rounded text-[18px]">arrow_back</span>
          Back
        </Link>

        <h1 className="font-display text-3xl text-mono-dark mb-2">Terms &amp; Conditions</h1>
        <p className="text-sm text-mono-light mb-10">Last updated: February 17, 2026</p>

        <div className="card p-8 space-y-8 text-sm text-mono-medium leading-relaxed">
          <section>
            <h2 className="text-lg text-mono-dark mb-3">1. Acceptance of Terms</h2>
            <p>
              By creating an account or using ExpenseTerminal (&ldquo;the Service&rdquo;), you agree to
              be bound by these Terms &amp; Conditions. If you do not agree, please do not use
              the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg text-mono-dark mb-3">2. Description of Service</h2>
            <p>
              ExpenseTerminal is a business expense tracking and tax deduction management tool.
              The Service uses artificial intelligence to categorize transactions and provide
              tax-related summaries. The Service does <strong>not</strong> provide tax, legal,
              or financial advice. Always consult a qualified professional for tax decisions.
            </p>
          </section>

          <section>
            <h2 className="text-lg text-mono-dark mb-3">3. User Accounts</h2>
            <p>
              You must provide accurate information when creating your account. You are
              responsible for maintaining the confidentiality of your credentials and for all
              activity under your account. Notify us immediately of any unauthorized use.
            </p>
          </section>

          <section>
            <h2 className="text-lg text-mono-dark mb-3">4. Your Data</h2>
            <p>
              You retain ownership of all financial data you upload. We process your data only
              to provide and improve the Service. We do not sell your data to third parties.
              See our <Link href="/privacy" className="text-accent-navy underline">Privacy Policy</Link>{" "}
              for details on data handling.
            </p>
          </section>

          <section>
            <h2 className="text-lg text-mono-dark mb-3">5. AI-Generated Content</h2>
            <p>
              Transaction categorizations, tax line assignments, and deduction estimates are
              generated by AI and may contain errors. You are responsible for reviewing and
              confirming all categorizations before filing taxes or making financial decisions.
            </p>
          </section>

          <section>
            <h2 className="text-lg text-mono-dark mb-3">6. Prohibited Uses</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>Use the Service for illegal purposes or to facilitate tax fraud</li>
              <li>Attempt to gain unauthorized access to other users&rsquo; accounts or data</li>
              <li>Reverse engineer, decompile, or disassemble any part of the Service</li>
              <li>Upload malicious content or interfere with the Service&rsquo;s operation</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg text-mono-dark mb-3">7. Limitation of Liability</h2>
            <p>
              The Service is provided &ldquo;as is&rdquo; without warranties of any kind. We are
              not liable for any tax penalties, missed deductions, or financial losses
              resulting from use of the Service. Maximum liability is limited to fees paid
              in the preceding 12 months.
            </p>
          </section>

          <section>
            <h2 className="text-lg text-mono-dark mb-3">8. Termination</h2>
            <p>
              We may suspend or terminate your account for violation of these terms. You may
              delete your account at any time. Upon termination, your data will be deleted
              within 30 days unless required by law.
            </p>
          </section>

          <section>
            <h2 className="text-lg text-mono-dark mb-3">9. Changes to Terms</h2>
            <p>
              We may update these terms from time to time. Material changes will be
              communicated via email or in-app notice. Continued use after changes constitutes
              acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-lg text-mono-dark mb-3">10. Contact</h2>
            <p>
              Questions about these terms? Email us at{" "}
              <a href="mailto:support@expenseteterminal.com" className="text-accent-navy underline">
                support@expenseteterminal.com
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
