import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-bg-secondary">
      <div className="max-w-[720px] mx-auto px-6 py-16">
        <Link
          href="/signup"
          className="inline-flex items-center gap-1.5 text-sm text-mono-light hover:text-mono-medium transition-colors mb-10"
        >
          <span className="material-symbols-rounded text-[18px]">arrow_back</span>
          Back
        </Link>

        <h1 className="font-display text-3xl text-mono-dark mb-2">Terms of Service</h1>
        <p className="text-sm text-mono-light mb-10">Effective Date: February 20, 2026</p>

        <div className="card p-8 space-y-8 text-sm text-mono-medium leading-relaxed">
          <section>
            <p className="mb-4">
              These Terms of Service (&ldquo;Terms&rdquo;) constitute a legally binding agreement between you (&ldquo;User,&rdquo; &ldquo;you,&rdquo; or &ldquo;your&rdquo;) and Smith Global LLC (&ldquo;Company,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;), governing your access to and use of ExpenseTerminal (the &ldquo;Platform&rdquo;). BY ACCESSING OR USING THE PLATFORM, YOU AGREE TO BE BOUND BY THESE TERMS. IF YOU DO NOT AGREE, DO NOT ACCESS OR USE THE PLATFORM.
            </p>
          </section>

          <section>
            <h2 className="text-lg text-mono-dark mb-3">1. Platform Description &amp; Scope</h2>
            <p>
              ExpenseTerminal is a software-as-a-service platform that enables users to upload financial data files (including CSV and similar formats) for the purpose of generating tax-related analysis, insights, and informational content. The Platform may integrate with third-party financial data aggregation services, including but not limited to Stripe Financial Connections and Plaid (collectively, &ldquo;Financial Data Partners&rdquo;).
            </p>
          </section>

          <section>
            <h2 className="text-lg text-mono-dark mb-3">2. Not Tax, Legal, or Financial Advice</h2>
            <p className="mb-3 font-semibold text-mono-dark">THIS IS THE MOST IMPORTANT SECTION. PLEASE READ CAREFULLY.</p>
            <p className="mb-2">
              All content, outputs, reports, summaries, calculations, and analyses generated by the Platform are provided for <strong>INFORMATIONAL AND EDUCATIONAL PURPOSES ONLY</strong>. Nothing on the Platform constitutes:
            </p>
            <ul className="list-disc pl-5 space-y-1 mb-3">
              <li>Tax advice, tax preparation, or tax filing services</li>
              <li>Legal advice or legal services of any kind</li>
              <li>Financial planning, investment, or accounting advice</li>
              <li>A substitute for consultation with a licensed CPA, tax attorney, enrolled agent, or other qualified professional</li>
            </ul>
            <p>
              Smith Global LLC is not a registered tax preparer, CPA firm, law firm, or financial advisory firm. No accountant-client, attorney-client, or fiduciary relationship is created by your use of the Platform. You bear sole and exclusive responsibility for all tax-related decisions and filings. The Company shall have no liability whatsoever for any tax positions taken, penalties incurred, or losses suffered based on information generated by the Platform.
            </p>
          </section>

          <section>
            <h2 className="text-lg text-mono-dark mb-3">3. Eligibility &amp; Account Requirements</h2>
            <p className="mb-2">
              You must be at least 18 years of age and have the legal capacity to enter into binding contracts. By creating an account, you represent and warrant that:
            </p>
            <ul className="list-disc pl-5 space-y-1 mb-3">
              <li>All registration information you provide is accurate, current, and complete</li>
              <li>You are using the Platform for lawful purposes only</li>
              <li>You are not located in a jurisdiction where use of the Platform is prohibited</li>
              <li>If acting on behalf of a business entity, you have authority to bind that entity to these Terms</li>
            </ul>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify us immediately at <a href="mailto:hello@expenseterminal.com" className="text-accent-navy underline">hello@expenseterminal.com</a> of any unauthorized access or breach.
            </p>
          </section>

          <section>
            <h2 className="text-lg text-mono-dark mb-3">4. Uploaded Data &amp; Financial Connections</h2>
            <h3 className="text-base text-mono-dark mb-2 mt-4">4.1 User-Uploaded Files</h3>
            <p className="mb-3">
              You retain all ownership rights to data you upload to the Platform. By uploading data, you grant the Company a limited, non-exclusive, royalty-free license to process, analyze, and display that data solely for the purpose of providing the Platform&apos;s services to you.
            </p>
            <h3 className="text-base text-mono-dark mb-2 mt-4">4.2 Third-Party Financial Data Connections</h3>
            <p className="mb-2">
              The Platform may connect to your financial accounts through Financial Data Partners (e.g., Plaid, Stripe Financial Connections). By authorizing such connections, you acknowledge and agree:
            </p>
            <ul className="list-disc pl-5 space-y-1 mb-3">
              <li>The Company is not responsible for the security, availability, or accuracy of data retrieved through Financial Data Partners</li>
              <li>Your use of Financial Data Partner connections is also governed by the Financial Data Partner&apos;s own terms and privacy policies</li>
              <li>You authorize the Company to retrieve, store, and process such financial data solely to provide the Platform&apos;s services</li>
              <li>You may revoke financial data connections at any time through your account settings or by contacting us</li>
            </ul>
            <h3 className="text-base text-mono-dark mb-2 mt-4">4.3 Data Accuracy</h3>
            <p>
              You are solely responsible for the accuracy and completeness of data you provide or authorize the Platform to retrieve. The Company makes no representations regarding the accuracy of data obtained from Financial Data Partners or user uploads. Outputs are only as reliable as the inputs provided.
            </p>
          </section>

          <section>
            <h2 className="text-lg text-mono-dark mb-3">5. Permitted &amp; Prohibited Uses</h2>
            <h3 className="text-base text-mono-dark mb-2 mt-4">5.1 Permitted Uses</h3>
            <p className="mb-3">
              You may use the Platform solely for your own lawful personal or internal business tax analysis purposes.
            </p>
            <h3 className="text-base text-mono-dark mb-2 mt-4">5.2 Prohibited Uses</h3>
            <p className="mb-2">You expressly agree NOT to:</p>
            <ul className="list-disc pl-5 space-y-1 mb-3">
              <li>Use the Platform to prepare or file tax returns on behalf of third parties without their explicit written consent</li>
              <li>Reverse engineer, decompile, disassemble, or attempt to extract source code from the Platform</li>
              <li>Scrape, crawl, or use automated tools to access or extract data from the Platform</li>
              <li>Upload data that you do not own or have the right to process</li>
              <li>Use the Platform for any fraudulent, deceptive, or illegal purpose, including tax fraud</li>
              <li>Resell, sublicense, or otherwise commercialize access to the Platform without written authorization</li>
              <li>Interfere with or disrupt the integrity, security, or performance of the Platform or its infrastructure</li>
              <li>Upload malicious code, viruses, or any content that could harm the Platform or other users</li>
            </ul>
            <p>
              Violation of these prohibitions may result in immediate termination of your account and may expose you to civil or criminal liability.
            </p>
          </section>

          <section>
            <h2 className="text-lg text-mono-dark mb-3">6. Intellectual Property</h2>
            <p className="mb-3">
              The Platform, including all software, algorithms, AI models, designs, interfaces, documentation, and content created by the Company, is and shall remain the exclusive intellectual property of Smith Global LLC and its licensors, protected under applicable copyright, trademark, trade secret, and other intellectual property laws. These Terms do not grant you any rights to the Company&apos;s intellectual property beyond the limited license to use the Platform as described herein.
            </p>
            <p>
              Any feedback, suggestions, or ideas you submit regarding the Platform may be used by the Company without restriction or compensation to you.
            </p>
          </section>

          <section>
            <h2 className="text-lg text-mono-dark mb-3">7. Subscription, Fees &amp; Billing</h2>
            <p className="mb-2">Access to certain features may require a paid subscription. By subscribing:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>You authorize us to charge your designated payment method on a recurring basis at the then-current subscription rate</li>
              <li>Fees are non-refundable except as expressly required by applicable law or as stated in our refund policy</li>
              <li>We reserve the right to modify pricing with 30 days&apos; notice; continued use after a price change constitutes acceptance</li>
              <li>Failure to pay may result in suspension or termination of your account</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg text-mono-dark mb-3">8. Disclaimer of Warranties</h2>
            <p>
              THE PLATFORM IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, COMPLETENESS, RELIABILITY, TITLE, AND NON-INFRINGEMENT. SMITH GLOBAL LLC DOES NOT WARRANT THAT THE PLATFORM WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. YOU USE THE PLATFORM ENTIRELY AT YOUR OWN RISK.
            </p>
          </section>

          <section>
            <h2 className="text-lg text-mono-dark mb-3">9. Limitation of Liability</h2>
            <p className="mb-3">
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL SMITH GLOBAL LLC, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AFFILIATES, OR LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO LOST PROFITS, LOST DATA, LOSS OF GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE OR SYSTEM FAILURE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
            </p>
            <p className="mb-3">
              IN ALL CASES, THE COMPANY&apos;S AGGREGATE CUMULATIVE LIABILITY TO YOU FOR ANY CLAIMS ARISING OUT OF OR RELATED TO THESE TERMS OR THE PLATFORM SHALL NOT EXCEED THE GREATER OF: (A) THE TOTAL FEES PAID BY YOU TO THE COMPANY IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR (B) ONE HUNDRED U.S. DOLLARS ($100.00).
            </p>
            <p>
              Some jurisdictions do not allow limitations on implied warranties or exclusion of incidental or consequential damages. In such jurisdictions, the above limitations shall apply to the maximum extent permitted by law.
            </p>
          </section>

          <section>
            <h2 className="text-lg text-mono-dark mb-3">10. Indemnification</h2>
            <p>
              You agree to indemnify, defend, and hold harmless Smith Global LLC and its officers, directors, employees, agents, affiliates, successors, and assigns from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys&apos; fees) arising out of or relating to: (a) your use of the Platform; (b) your violation of these Terms; (c) your violation of any applicable law or regulation, including tax laws; (d) your infringement of any third-party right; (e) any data you upload or authorize the Platform to access; or (f) any reliance on Platform outputs for tax, legal, or financial decisions.
            </p>
          </section>

          <section>
            <h2 className="text-lg text-mono-dark mb-3">11. Third-Party Services &amp; Links</h2>
            <p>
              The Platform may integrate with or link to third-party services, including Financial Data Partners and payment processors. The Company does not control these third parties and is not responsible for their content, privacy practices, or conduct. Your interactions with third-party services are governed exclusively by their respective terms and policies. We encourage you to review those policies carefully.
            </p>
          </section>

          <section>
            <h2 className="text-lg text-mono-dark mb-3">12. Term, Suspension &amp; Termination</h2>
            <p>
              These Terms remain in effect for as long as you use the Platform. We reserve the right to suspend or terminate your access immediately and without prior notice for any violation of these Terms, fraudulent activity, illegal use, or for any other reason in our sole discretion. Upon termination, your right to use the Platform ceases immediately. Sections 2, 6, 8, 9, 10, 13, 14, and 15 shall survive termination.
            </p>
          </section>

          <section>
            <h2 className="text-lg text-mono-dark mb-3">13. Governing Law &amp; Dispute Resolution</h2>
            <h3 className="text-base text-mono-dark mb-2 mt-4">13.1 Governing Law</h3>
            <p className="mb-3">
              These Terms shall be governed by and construed in accordance with the laws of the State of New Jersey, without regard to its conflict of law provisions.
            </p>
            <h3 className="text-base text-mono-dark mb-2 mt-4">13.2 Mandatory Arbitration</h3>
            <p className="mb-2 font-semibold text-mono-dark">PLEASE READ THIS SECTION CAREFULLY. IT AFFECTS YOUR LEGAL RIGHTS.</p>
            <p className="mb-3">
              Any dispute, claim, or controversy arising out of or relating to these Terms or the Platform shall be resolved by binding individual arbitration under the rules of the American Arbitration Association (AAA), rather than in court. YOU WAIVE YOUR RIGHT TO A JURY TRIAL AND YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION, CLASS ARBITRATION, OR REPRESENTATIVE ACTION. Arbitration shall take place in Tenafly, New Jersey.
            </p>
            <p className="mb-3">
              Notwithstanding the foregoing, either party may seek emergency injunctive or equitable relief in any court of competent jurisdiction to prevent irreparable harm.
            </p>
            <h3 className="text-base text-mono-dark mb-2 mt-4">13.3 Time Limitation on Claims</h3>
            <p>
              Any claim or cause of action arising out of or relating to these Terms or the Platform must be brought within one (1) year after it arises, or it is permanently barred.
            </p>
          </section>

          <section>
            <h2 className="text-lg text-mono-dark mb-3">14. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. Material changes will be communicated via email to your registered address or through a prominent notice on the Platform. Your continued use of the Platform after the effective date of revised Terms constitutes your acceptance of the changes. If you do not agree, you must discontinue use of the Platform.
            </p>
          </section>

          <section>
            <h2 className="text-lg text-mono-dark mb-3">15. General Provisions</h2>
            <p className="mb-2">
              <strong>Entire Agreement:</strong> These Terms, together with our <Link href="/privacy" className="text-accent-navy underline">Privacy Policy</Link>, constitute the entire agreement between you and the Company regarding the Platform.
            </p>
            <p className="mb-2">
              <strong>Severability:</strong> If any provision is found unenforceable, the remaining provisions remain in full force.
            </p>
            <p className="mb-2">
              <strong>Waiver:</strong> Failure to enforce any right or provision shall not constitute a waiver of that right.
            </p>
            <p className="mb-2">
              <strong>Assignment:</strong> You may not assign your rights or obligations under these Terms without our prior written consent. We may assign our rights freely.
            </p>
            <p className="mb-2">
              <strong>Notices:</strong> Legal notices to the Company must be sent to <a href="mailto:hello@expenseterminal.com" className="text-accent-navy underline">hello@expenseterminal.com</a>.
            </p>
            <p>
              <strong>Force Majeure:</strong> The Company shall not be liable for delays or failures in performance resulting from circumstances beyond its reasonable control.
            </p>
          </section>

          <section>
            <p>
              For questions about these Terms, contact us at: <a href="mailto:hello@expenseterminal.com" className="text-accent-navy underline">hello@expenseterminal.com</a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
